[package]
name = "pointguard_types"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
schemars = "0.8.16"
serde = "1.0.193"
serde_json = "1.0.108"
